# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [8.x, 10.x, 12.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        architecture: [x86, x64, arm64, armv6l, armv7l, ppc64le, s390x]
        exclude:
        
          - os: ubuntu-latest
            node-version: 10.x
            architecture: x86
            
          - os: ubuntu-latest
            node-version: 12.x
            architecture: x86
            
          - os: ubuntu-latest
            node-version: 14.x
            architecture: x86
            
          - os: ubuntu-latest
            node-version: 15.x
            architecture: x86
          - os: ubuntu-latest
            node-version: 15.x
            architecture: armv6l
            
          - os: ubuntu-latest
            node-version: 16.x
            architecture: x86
          - os: ubuntu-latest
            node-version: 16.x
            architecture: armv6l
            
          - os: macos-latest
            node-version: 8.x
            architecture: x86
          - os: macos-latest
            node-version: 8.x
            architecture: arm64
          - os: macos-latest
            node-version: 8.x
            architecture: armv6l
          - os: macos-latest
            node-version: 8.x
            architecture: armv7l
          - os: macos-latest
            node-version: 8.x
            architecture: ppc64le
          - os: macos-latest
            node-version: 8.x
            architecture: s390x

          - os: macos-latest
            node-version: 10.x
            architecture: x86
          - os: macos-latest
            node-version: 10.x
            architecture: arm64
          - os: macos-latest
            node-version: 10.x
            architecture: armv6l
          - os: macos-latest
            node-version: 10.x
            architecture: armv7l
          - os: macos-latest
            node-version: 10.x
            architecture: ppc64le
          - os: macos-latest
            node-version: 10.x
            architecture: s390x

          - os: macos-latest
            node-version: 12.x
            architecture: x86
          - os: macos-latest
            node-version: 12.x
            architecture: arm64
          - os: macos-latest
            node-version: 12.x
            architecture: armv6l
          - os: macos-latest
            node-version: 12.x
            architecture: armv7l
          - os: macos-latest
            node-version: 12.x
            architecture: ppc64le
          - os: macos-latest
            node-version: 12.x
            architecture: s390x
            
          - os: macos-latest
            node-version: 14.x
            architecture: x86
          - os: macos-latest
            node-version: 14.x
            architecture: arm64
          - os: macos-latest
            node-version: 14.x
            architecture: armv6l
          - os: macos-latest
            node-version: 14.x
            architecture: armv7l
          - os: macos-latest
            node-version: 14.x
            architecture: ppc64le
          - os: macos-latest
            node-version: 14.x
            architecture: s390x

          - os: macos-latest
            node-version: 15.x
            architecture: x86
          - os: macos-latest
            node-version: 15.x
            architecture: arm64
          - os: macos-latest
            node-version: 15.x
            architecture: armv6l
          - os: macos-latest
            node-version: 15.x
            architecture: armv7l
          - os: macos-latest
            node-version: 15.x
            architecture: ppc64le
          - os: macos-latest
            node-version: 15.x
            architecture: s390x
            
          - os: macos-latest
            node-version: 16.x
            architecture: x86
          - os: macos-latest
            node-version: 16.x
            architecture: armv6l
          - os: macos-latest
            node-version: 16.x
            architecture: armv7l
          - os: macos-latest
            node-version: 16.x
            architecture: ppc64le
          - os: macos-latest
            node-version: 16.x
            architecture: s390x
            
          - os: windows-latest
            node-version: 8.x
            architecture: arm64
          - os: windows-latest
            node-version: 8.x
            architecture: armv6l
          - os: windows-latest
            node-version: 8.x
            architecture: armv7l
          - os: windows-latest
            node-version: 8.x
            architecture: ppc64le
          - os: windows-latest
            node-version: 8.x
            architecture: s390x

          - os: windows-latest
            node-version: 10.x
            architecture: arm64
          - os: windows-latest
            node-version: 10.x
            architecture: armv6l
          - os: windows-latest
            node-version: 10.x
            architecture: armv7l
          - os: windows-latest
            node-version: 10.x
            architecture: ppc64le
          - os: windows-latest
            node-version: 10.x
            architecture: s390x
            
          - os: windows-latest
            node-version: 12.x
            architecture: arm64
          - os: windows-latest
            node-version: 12.x
            architecture: armv6l
          - os: windows-latest
            node-version: 12.x
            architecture: armv7l
          - os: windows-latest
            node-version: 12.x
            architecture: ppc64le
          - os: windows-latest
            node-version: 12.x
            architecture: s390x
            
          - os: windows-latest
            node-version: 14.x
            architecture: arm64
          - os: windows-latest
            node-version: 14.x
            architecture: armv6l
          - os: windows-latest
            node-version: 14.x
            architecture: armv7l
          - os: windows-latest
            node-version: 14.x
            architecture: ppc64le
          - os: windows-latest
            node-version: 14.x
            architecture: s390x
            
          - os: windows-latest
            node-version: 15.x
            architecture: arm64
          - os: windows-latest
            node-version: 15.x
            architecture: armv6l
          - os: windows-latest
            node-version: 15.x
            architecture: armv7l
          - os: windows-latest
            node-version: 15.x
            architecture: ppc64le
          - os: windows-latest
            node-version: 15.x
            architecture: s390x

          - os: windows-latest
            node-version: 16.x
            architecture: arm64
          - os: windows-latest
            node-version: 16.x
            architecture: armv6l
          - os: windows-latest
            node-version: 16.x
            architecture: armv7l
          - os: windows-latest
            node-version: 16.x
            architecture: ppc64le
          - os: windows-latest
            node-version: 16.x
            architecture: s390x
            
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
        check-latest: true
#     - name: Install Yarn
#       run: npm install -g yarn
    - name: Install dependencies
      run: yarn install
    - name: Running tests
      run: yarn test
